### ISSUE TITLE
Pokedex Capstone Project

### ISSUE THREAD

**Issue by techEmprez** [techEmprez/Pokedex#21]
### Project Link and template:
- [Pokedex](https://github.com/techEmprez/Pokedex/issues/21)
 - [ TEMPLATE   ](https://github.com/techEmprez/Pokedex/projects/5)
 

**This project involves 3 people;**

### Group Tasks
- [0.5pt] Find external API - group task
- [0.5pt] Set up the project with Webpack and Jest- group task
- [1pt] Choose assets - group task
- [0.5pt] Add header - group task
- [0.5pt] Add footer - group task

### Individual Tasks

- **@techEmprez** 
[4pt]  Display list of items on the Homepage 
[4pt]  - Display number of likes for each item on the Homepage 
[3pt]  - Create feature: add  new like 
[3pt]  - Add all items counter on the Homepage 
[3pt]  - Add tests for items counter 

- @X-Elie-X 
[4pt]  -Display Comments pop up with selected item's details 
[3pt]  - Display comments for a given item on the Comments pop-up 
[4pt]  - Create feature: add new comment 
[3pt]  - Add comments counter 
[3pt]  - Add tests for comments counter 

- @TemesgenA 
[4pt]  - Display Reservations pop up with selected item's details 
[3pt]  - Display reservations for a given item on the Reservations pop-up 
[4pt]  - Create feature: add new reservation 
[3pt]  - Add reservations counter 
[3pt]  - Add tests for reservations counter

**Comment by muneebulrehman** [comment]
Hi @team, 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] All the tasks should be assigned to each partner and the group tasks should be assigned to the whole group. Kindly do so and submit it for the re-review.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by techEmprez** [comment]
Group task and individual task has been assigned.

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @techEmprez, @TemesgenA  & @X-Elie-X, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] Kindly make sure you assign all the cards. Like all group tasks to all 3 members.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShahierNashaat** [comment]
Hi @techEmprez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by techEmprez** [comment]
Thank you
